### ISSUE TITLE
It still fails to work! 

### ISSUE THREAD

**Issue by JingangLang** [tushortz/Pygame-Completions#1]
Firstly, thanks for your help. But, why it still fails to work after I handle it with your guidance.I wrote a small game using the module of pygame,which went well at IDLE while appeared wrong at the Sublime Text.I will be appreciated if you can help me find out the solution of this problem.Please.Thank you.

**Comment by tushortz** [comment]
What do you mean by `it appear wrong` @JingangLang

**Comment by JingangLang** [comment]
It still shows that no module named 'pygame'

**Comment by JingangLang** [comment]
OK！I did it .The reason is that  the previous version of pygame is not suitable for python3.5 .Thanks for your help again.

**Comment by tushortz** [comment]
no worries @JingangLang
